apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aumigos-components
  annotations:
    backstage.io/user-org: aumigos
spec:
  targets:
    - ./components/meu-microservico-da-aumigos.yaml
